import { existsSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { DIAGNOSTIC_CODES, fail, ok, type Result } from '@atarashi/schema';

export type TargetState =
    | { kind: 'missing' }
    | { kind: 'empty' }
    | { kind: 'non-empty'; entries: string[] }
    | { kind: 'generated' };

/** Files that do not make a directory "non-empty" for our purposes. */
const IGNORABLE = new Set(['.DS_Store', 'Thumbs.db', '.git']);

export function inspectTarget(targetDir: string): TargetState {
    if (!existsSync(targetDir)) return { kind: 'missing' };

    const stats = statSync(targetDir);
    if (!stats.isDirectory()) {
        return { kind: 'non-empty', entries: [targetDir] };
    }

    if (existsSync(join(targetDir, 'atarashi.json'))) return { kind: 'generated' };

    const entries = readdirSync(targetDir).filter((entry) => !IGNORABLE.has(entry));
    return entries.length === 0 ? { kind: 'empty' } : { kind: 'non-empty', entries };
}

/**
 * Decides whether writing may proceed. v0.6 called a non-recursive `mkdirSync`
 * and threw a raw stack trace at the user; every one of those cases is an
 * explicit, explained outcome here.
 */
export function preflight(targetDir: string, options: { force: boolean }): Result<TargetState> {
    const state = inspectTarget(targetDir);

    if (state.kind === 'generated' && !options.force) {
        return fail(
            DIAGNOSTIC_CODES.TARGET_NOT_EMPTY,
            `\`${targetDir}\` already contains an Atarashi project`,
            [
                {
                    severity: 'error',
                    code: DIAGNOSTIC_CODES.TARGET_NOT_EMPTY,
                    message: 'This directory was generated by Atarashi already',
                    suggestions: [
                        'Add a capability to it instead: `atarashi add <blueprint>`',
                        'Or pass `--force` to regenerate over it',
                    ],
                },
            ]
        );
    }

    if (state.kind === 'non-empty' && !options.force) {
        const preview = state.entries.slice(0, 5).join(', ');
        const more = state.entries.length > 5 ? `, and ${state.entries.length - 5} more` : '';
        return fail(
            DIAGNOSTIC_CODES.TARGET_NOT_EMPTY,
            `\`${targetDir}\` is not empty (${preview}${more})`,
            [
                {
                    severity: 'error',
                    code: DIAGNOSTIC_CODES.TARGET_NOT_EMPTY,
                    message: 'Refusing to write into a directory that already has files in it',
                    suggestions: [
                        'Pass `--force` to merge into it',
                        'Or choose an empty directory',
                    ],
                },
            ]
        );
    }

    return ok(state);
}
