import { DIAGNOSTIC_CODES } from '@atarashi/schema';

/** Doc 04 — CLI Reference § Exit codes. */
export const EXIT = {
    OK: 0,
    RUNTIME: 1,
    USAGE: 2,
    RESOLUTION: 3,
    MERGE_CONFLICT: 4,
    FS_REFUSAL: 5,
    REGISTRY: 6,
    POST_ACTION: 7,
    INTERRUPTED: 130,
} as const;

export type ExitCode = (typeof EXIT)[keyof typeof EXIT];

const CODE_TO_EXIT: Record<string, number> = {
    [DIAGNOSTIC_CODES.UNKNOWN_BLUEPRINT]: EXIT.RESOLUTION,
    [DIAGNOSTIC_CODES.UNSATISFIED_REQUIREMENT]: EXIT.RESOLUTION,
    [DIAGNOSTIC_CODES.AMBIGUOUS_REQUIREMENT]: EXIT.RESOLUTION,
    [DIAGNOSTIC_CODES.CAPABILITY_CONFLICT]: EXIT.RESOLUTION,
    [DIAGNOSTIC_CODES.DEPENDENCY_CYCLE]: EXIT.RESOLUTION,
    [DIAGNOSTIC_CODES.ENGINE_INCOMPATIBLE]: EXIT.RESOLUTION,

    [DIAGNOSTIC_CODES.PROMPT_NAME_COLLISION]: EXIT.USAGE,
    [DIAGNOSTIC_CODES.MISSING_ANSWER]: EXIT.USAGE,
    [DIAGNOSTIC_CODES.INVALID_ANSWER]: EXIT.USAGE,

    [DIAGNOSTIC_CODES.RENDER_FAILED]: EXIT.RUNTIME,
    [DIAGNOSTIC_CODES.EXPRESSION_FAILED]: EXIT.RUNTIME,
    [DIAGNOSTIC_CODES.MERGE_CONFLICT]: EXIT.MERGE_CONFLICT,
    [DIAGNOSTIC_CODES.VERSION_RANGE_CONFLICT]: EXIT.MERGE_CONFLICT,

    [DIAGNOSTIC_CODES.PATH_ESCAPE]: EXIT.FS_REFUSAL,
    [DIAGNOSTIC_CODES.PATH_CASE_COLLISION]: EXIT.FS_REFUSAL,
    [DIAGNOSTIC_CODES.FILE_TOO_LARGE]: EXIT.FS_REFUSAL,
    [DIAGNOSTIC_CODES.INVALID_GENERATED_JSON]: EXIT.RUNTIME,
    [DIAGNOSTIC_CODES.TARGET_NOT_EMPTY]: EXIT.FS_REFUSAL,
    [DIAGNOSTIC_CODES.WRITE_FAILED]: EXIT.FS_REFUSAL,
    [DIAGNOSTIC_CODES.INTERRUPTED]: EXIT.INTERRUPTED,

    [DIAGNOSTIC_CODES.ACTION_FAILED]: EXIT.POST_ACTION,
    [DIAGNOSTIC_CODES.REGISTRY_UNAVAILABLE]: EXIT.REGISTRY,
    [DIAGNOSTIC_CODES.INTEGRITY_MISMATCH]: EXIT.REGISTRY,

    [DIAGNOSTIC_CODES.SPEC_VERSION_UNSUPPORTED]: EXIT.USAGE,
    [DIAGNOSTIC_CODES.MANIFEST_VERSION_UNSUPPORTED]: EXIT.USAGE,
    [DIAGNOSTIC_CODES.SCHEMA_INVALID]: EXIT.USAGE,
};

/** Falls back to a generic runtime failure for anything not in the table. */
export function exitCodeFor(code: string): number {
    return CODE_TO_EXIT[code] ?? EXIT.RUNTIME;
}
