#!/usr/bin/env node
// Generates the parts of the documentation that have a single source of truth
// somewhere else, so they cannot drift from the thing they describe:
//
//   docs/guide/cli.md            ← the binary's own `--help` output
//   docs/guide/blueprints.md     ← every blueprint manifest
//   docs/guide/presets/*.md      ← a real generation plan per preset
//   packages/blueprints/blueprints/<id>/README.md
//
// The hand-written guides (getting started, authoring, configuration, recipes,
// troubleshooting) are not touched.
//
//   node scripts/build-docs.mjs           write the files
//   node scripts/build-docs.mjs --check   fail if they are out of date
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Catalogue, planFor, specForPreset } from '@atarashi/testing';

const root = fileURLToPath(new URL('..', import.meta.url));
const cli = join(root, 'packages/cli/dist/cli.js');
const blueprintsRoot = join(root, 'packages/blueprints');
const guideDir = join(root, 'docs/guide');

const CHECK = process.argv.includes('--check');
const GENERATED = '<!-- Generated by `pnpm build:docs`. Do not edit by hand. -->';

const written = [];
const stale = [];

function emit(path, contents) {
    const body = contents.endsWith('\n') ? contents : `${contents}\n`;
    let current;
    try {
        current = readFileSync(path, 'utf8');
    } catch {
        current = undefined;
    }
    if (current === body) return;
    if (CHECK) {
        stale.push(path.slice(root.length));
        return;
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body, 'utf8');
    written.push(path.slice(root.length));
}

const help = (args) => {
    const result = spawnSync(process.execPath, [cli, ...args], { encoding: 'utf8' });
    return `${result.stdout ?? ''}${result.stderr ?? ''}`.trimEnd();
};

const fence = (text, lang = 'text') => `\`\`\`${lang}\n${text}\n\`\`\``;
const escapePipes = (text) => String(text).replaceAll('|', '\\|');

/**
 * A `to`/`target` path is a template, and almost every one of them is the same
 * language conditional. Collapse that to `ts|js` so a reader sees a path rather
 * than a Handlebars block; anything else is left visible on purpose.
 */
const readablePath = (path) =>
    String(path).replace(/\{\{#when\s+"[^"]*"\}\}(.*?)\{\{else\}\}(.*?)\{\{\/when\}\}/g, '$1|$2');
const anchor = (id) => id.replace('/', '-');

// ── docs/guide/cli.md ────────────────────────────────────────────────────────

function exitCodes() {
    const source = readFileSync(join(root, 'packages/cli/src/exit-codes.ts'), 'utf8');
    const rows = [];
    for (const match of source.matchAll(/(?:\/\*\*\s*(.*?)\s*\*\/\s*)?([A-Z_]+):\s*(\d+)/g)) {
        rows.push({ name: match[2], code: match[3], note: match[1] ?? '' });
    }
    return rows;
}

function cliReference() {
    const commands = [
        ['atarashi new', ['new', '--help']],
        ['atarashi add', ['add', '--help']],
    ];

    const sections = commands
        .map(([title, args]) => `### \`${title}\`\n\n${fence(help(args))}`)
        .join('\n\n');

    const codes = exitCodes()
        .map((row) => `| \`${row.code}\` | ${row.name} | ${escapePipes(row.note)} |`)
        .join('\n');

    return `# CLI reference

${GENERATED}

Every command, printed by the binary itself. If something here disagrees with
what \`atarashi --help\` tells you, the binary is right and this page is stale;
run \`pnpm build:docs\`.

## Commands

${fence(help([]))}

${sections}

## Exit codes

Scripts can branch on these; they are part of the public surface and do not
change within a major version.

| Code | Name | Meaning |
|------|------|---------|
${codes}

## Global behaviour

- **\`--json\`** switches every command to a machine-readable object on stdout
  and implies \`--no-color\`. Human-readable progress goes to stderr, so
  \`atarashi new … --json > plan.json\` is safe to pipe.
- **Non-TTY** runs never prompt. A missing required answer is an error that
  names the exact flag to pass, rather than a hang.
- **\`--offline\`** uses only what is already in the cache; the bundled
  blueprints always resolve, so a first run works with no network.
`;
}

// ── Per-blueprint README + the catalogue ─────────────────────────────────────

const CATEGORY_ORDER = [
    'runtime',
    'http',
    'database',
    'orm',
    'auth',
    'validation',
    'middleware',
    'observability',
    'linting',
    'testing',
    'infrastructure',
    'ci',
    'web',
    'meta',
];

const categoryRank = (name) => {
    const index = CATEGORY_ORDER.indexOf(name);
    return index === -1 ? CATEGORY_ORDER.length : index;
};

function blueprintReadme(manifest) {
    const lines = [`# \`${manifest.id}\``, '', GENERATED, '', manifest.description, ''];

    const list = (label, values) => {
        if (!values || values.length === 0) return;
        lines.push(`**${label}:** ${values.map((v) => `\`${v}\``).join(', ')}`, '');
    };

    list('Provides', manifest.provides);
    list('Requires', manifest.requires);
    list('Conflicts with', manifest.conflicts);

    if (manifest.prompts?.length) {
        lines.push('## Options', '', '| Prompt | Flag | Type | Default |', '|---|---|---|---|');
        for (const prompt of manifest.prompts) {
            const flag = prompt.flag ? `\`${prompt.flag}\`` : '-';
            const fallback =
                prompt.default === undefined ? '-' : `\`${JSON.stringify(prompt.default)}\``;
            lines.push(
                `| \`${prompt.name}\` | ${flag} | ${prompt.type} | ${escapePipes(fallback)} |`
            );
        }
        lines.push('');
    }

    const files = manifest.files ?? [];
    if (files.length > 0) {
        lines.push('## Files it writes', '');
        for (const file of files) {
            const when = file.when ? ` (when \`${file.when}\`)` : '';
            lines.push(`- \`${readablePath(file.to ?? file.from)}\`${when}`);
        }
        lines.push('');
    }

    const deps = Object.entries(manifest.dependencies ?? {});
    const devDeps = Object.entries(manifest.devDependencies ?? {});
    if (deps.length + devDeps.length > 0) {
        lines.push('## Dependencies', '');
        const render = ([name, spec]) => {
            const range = typeof spec === 'string' ? spec : (spec.version ?? 'from the registry');
            const when = typeof spec === 'object' && spec.when ? ` (when \`${spec.when}\`)` : '';
            return `- \`${name}@${range}\`${when}`;
        };
        if (deps.length) lines.push(...deps.map(render), '');
        if (devDeps.length) lines.push('Development only:', '', ...devDeps.map(render), '');
    }

    if (manifest.env?.length) {
        lines.push('## Environment', '', '| Variable | Required | Description |', '|---|---|---|');
        for (const entry of manifest.env) {
            lines.push(
                `| \`${entry.key}\` | ${entry.required ? 'yes' : 'no'} | ${escapePipes(entry.description ?? '')} |`
            );
        }
        lines.push('');
    }

    const slots = (manifest.contributions ?? []).filter((c) => c.slot);
    if (slots.length > 0) {
        lines.push(
            '## What it contributes to other files',
            '',
            '| File | Slot | Line |',
            '|---|---|---|',
            ...slots.map(
                (c) =>
                    `| \`${escapePipes(readablePath(c.target))}\` | \`${c.slot}\` | \`${escapePipes(c.value.split('\n')[0])}\` |`
            ),
            ''
        );
    }

    const merges = (manifest.contributions ?? []).filter((c) => c.merge);
    if (merges.length > 0) {
        lines.push(
            '## What it merges into other files',
            '',
            ...merges.map((c) => `- \`${readablePath(c.target)}\` (\`${c.merge}\`)`),
            ''
        );
    }

    lines.push(
        '## Use it',
        '',
        fence(`atarashi new my-app --add ${manifest.id}\natarashi add ${manifest.id}`, 'bash'),
        '',
        `Version ${manifest.version}. Format reference: [Authoring blueprints](../../../../docs/guide/authoring-blueprints.md).`
    );

    return lines.join('\n');
}

function catalogue(manifests) {
    const byCategory = new Map();
    for (const manifest of manifests) {
        const bucket = byCategory.get(manifest.category) ?? [];
        bucket.push(manifest);
        byCategory.set(manifest.category, bucket);
    }

    const sections = [...byCategory.entries()]
        .sort((a, b) => categoryRank(a[0]) - categoryRank(b[0]) || (a[0] < b[0] ? -1 : 1))
        .map(([category, entries]) => {
            const rows = entries
                .sort((a, b) => (a.id < b.id ? -1 : 1))
                .map(
                    (manifest) =>
                        `| [\`${manifest.id}\`](#${anchor(manifest.id)}) | ${escapePipes(manifest.description)} | ${manifest.provides.map((p) => `\`${p}\``).join(' ') || '-'} |`
                )
                .join('\n');
            return `### ${category}\n\n| Blueprint | What it does | Provides |\n|---|---|---|\n${rows}`;
        })
        .join('\n\n');

    const details = manifests
        .sort((a, b) => (a.id < b.id ? -1 : 1))
        .map((manifest) => {
            const requires = manifest.requires.length
                ? manifest.requires.map((r) => `\`${r}\``).join(', ')
                : 'nothing';
            const conflicts = manifest.conflicts.length
                ? `, conflicts on ${manifest.conflicts.map((c) => `\`${c}\``).join(', ')}`
                : '';
            return [
                `#### \`${manifest.id}\``,
                '',
                manifest.description,
                '',
                `Requires ${requires}${conflicts}.`,
                '',
                `[Full reference →](../../packages/blueprints/blueprints/${manifest.id}/README.md)`,
            ].join('\n');
        })
        .join('\n\n');

    return `# Blueprint catalogue

${GENERATED}

${manifests.length} first-party blueprints. Every one of them is a directory with
a manifest; nothing about them is privileged, and a blueprint you write works
the same way. See [Authoring blueprints](./authoring-blueprints.md).

Pick them with \`--add\`, or let a [preset](./presets/) pick a coherent set for
you:

${fence('atarashi new my-api --add http/fastify --add db/postgres --add orm/drizzle', 'bash')}

Blueprints declare capabilities rather than naming each other, so the resolver
pulls in what is missing and refuses combinations that cannot coexist. Two
blueprints that both \`provide\` \`database\` will not install together, and it
will tell you which ones to choose between.

## By category

${sections}

## Every blueprint

${details}
`;
}

// ── Preset pages ─────────────────────────────────────────────────────────────

function fileTree(paths) {
    const root = new Map();
    for (const path of [...paths].sort()) {
        let node = root;
        for (const part of path.split('/')) {
            if (!node.has(part)) node.set(part, new Map());
            node = node.get(part);
        }
    }

    const lines = [];
    const walk = (node, prefix) => {
        const entries = [...node.entries()].sort(([a, aKids], [b, bKids]) => {
            const aDir = aKids.size > 0;
            const bDir = bKids.size > 0;
            if (aDir !== bDir) return aDir ? -1 : 1;
            return a < b ? -1 : 1;
        });
        entries.forEach(([name, kids], index) => {
            const last = index === entries.length - 1;
            lines.push(`${prefix}${last ? '└── ' : '├── '}${name}${kids.size > 0 ? '/' : ''}`);
            if (kids.size > 0) walk(kids, `${prefix}${last ? '    ' : '│   '}`);
        });
    };
    walk(root, '');
    return lines.join('\n');
}

async function presetPage(cat, preset) {
    const id = preset.id.replace(/^preset\//, '');
    const spec = await specForPreset(cat, preset.id, { name: 'my-app' });
    const result = await planFor(cat, spec);
    if (!result.ok) throw new Error(`preset ${preset.id} does not plan: ${result.error.message}`);
    const plan = result.value;

    const deps = plan.summary.deps.dependencies ?? [];
    const devDeps = plan.summary.deps.devDependencies ?? [];
    const depLine = (dep) => `- \`${dep.name}@${dep.range}\``;

    return `# ${preset.name}

${GENERATED}

${preset.description}

${fence(`atarashi new my-app --preset ${id}`, 'bash')}

## What you get

${preset.blueprints.map((blueprint) => `- [\`${blueprint}\`](../../../packages/blueprints/blueprints/${blueprint}/README.md)`).join('\n')}

## Files

${plan.files.length} files, ${(plan.summary.totalBytes / 1024).toFixed(1)} KB before \`node_modules\`.

${fence(`my-app/\n${fileTree(plan.files.map((file) => file.path))}`)}

## Dependencies

${deps.length ? deps.map(depLine).join('\n') : '_None._'}

${devDeps.length ? `Development only:\n\n${devDeps.map(depLine).join('\n')}` : ''}

## After generating

${plan.summary.nextSteps.map((step, index) => `${index + 1}. ${step}`).join('\n')}

## Change it

A preset is a starting point, not a cage. Add to it, drop from it, or eject:

${fence(
    [
        `atarashi new my-app --preset ${id} --add obs/pino`,
        `atarashi new my-app --preset ${id} --remove lint/biome --add lint/eslint-prettier`,
        `atarashi add auth/jwt   # later, inside the generated project`,
    ].join('\n'),
    'bash'
)}
`;
}

function presetIndex(presets) {
    const rows = presets
        .map((preset) => {
            const id = preset.id.replace(/^preset\//, '');
            return `| [${preset.name}](./${id}.md) | \`--preset ${id}\` | ${escapePipes(preset.description)} |`;
        })
        .join('\n');

    return `# Presets

${GENERATED}

A preset is a named list of blueprints that are known to work together. It saves
you from assembling the same five or six every time, and it is the fastest way
to see what Atarashi produces.

| Preset | Flag | What it is |
|---|---|---|
${rows}

Nothing about a preset is fixed: \`--add\` and \`--remove\` adjust one before it
generates, and \`atarashi preset save\` turns a project you like into a preset of
your own.
`;
}

// ── Run ──────────────────────────────────────────────────────────────────────

const cat = new Catalogue(blueprintsRoot);
const ids = await cat.ids();
const manifests = [];
for (const id of ids) {
    const loaded = await cat.load(id);
    if (loaded) manifests.push(loaded.manifest);
}

emit(join(guideDir, 'cli.md'), cliReference());
emit(join(guideDir, 'blueprints.md'), catalogue(manifests));

for (const manifest of manifests) {
    emit(join(blueprintsRoot, 'blueprints', manifest.id, 'README.md'), blueprintReadme(manifest));
}

const presets = (await cat.presets()).sort((a, b) => (a.id < b.id ? -1 : 1));
emit(join(guideDir, 'presets/README.md'), presetIndex(presets));
for (const preset of presets) {
    const id = preset.id.replace(/^preset\//, '');
    emit(join(guideDir, 'presets', `${id}.md`), await presetPage(cat, preset));
}

if (CHECK) {
    if (stale.length === 0) {
        console.log(`✔ docs are up to date (${ids.length} blueprints, ${presets.length} presets)`);
        process.exit(0);
    }
    console.error(`✖ ${stale.length} generated doc(s) are out of date — run \`pnpm build:docs\`:`);
    for (const path of stale) console.error(`    ${path}`);
    process.exit(1);
}

console.log(
    written.length === 0
        ? '✔ docs already up to date'
        : `✔ wrote ${written.length} file(s) — ${ids.length} blueprints, ${presets.length} presets`
);
